# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otZFtf9WMRAAM3vN7gWq6FK-O7ff9hE8

# **Calculator Using Python**
"""

# functions for each operation

#Addition
def add(x, y):
    return x + y
#Subtraction
def subtract(x, y):
    return x - y
#Multiplication
def multiply(x, y):
    return x * y
#Division
def divide(x, y):
    return x / y

#printing Choices
print("Select operation.")
choice = input("Choose \n 1 for Addition\n 2 for Subtraction\n 3 for Multiplication\n 4 for Division\n")

#Taking input
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

if choice == '1':
    print(num1, "+", num2, "=", add(num1, num2))

elif choice == '2':
    print(num1, "-", num2, "=", subtract(num1, num2))

elif choice == '3':
    print(num1, "*", num2, "=", multiply(num1, num2))

elif choice == '4':
    print(num1, "/", num2, "=", divide(num1, num2))

else:
    print("Invalid input")