# -*- coding: utf-8 -*-
"""TypingTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CrVnriGykLXnE7Q3aOB8CEBCd4acNQEe

# **Speed Typing Test**
"""

''' the Python time module enables working with time in Python. It provides features like obtaining the current 
datetime and the functionality to delay the programme's execution.'''

import time

def speed_typing_test():
    # prompt user to start the test
    input("Press Enter to start the typing test...")
    
    # set up the test
    inp_text = "Join the Virtual Internship Program in emerging technologies with CodeClause"
    print("start Typing the following text:\n")
    print(inp_text + "\n")
    
    #start time
    starting_time = time.time()
    
    # asking the user to start typing
    user_input = input()
    
    # end time
    ending_time = time.time()
    
    # calculate total time taken
    time_taken = ending_time - starting_time
    total_words_typed = len(user_input.split())
    wpm = total_words_typed / (time_taken / 60)
    
    print("You typed", total_words_typed, "words in", round(time_taken, 2), "seconds.")
    print("That's a speed of", round(wpm, 2), "words per minute!")

# run the test
speed_typing_test()